name: Build wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_BEFORE_BUILD: "pip install nanobind"
          CIBW_ENVIRONMENT: "CMAKE_ARGS='' MACOSX_DEPLOYMENT_TARGET='10.14'"
          CIBW_TEST_REQUIRES: "pytest pytest-rerunfailures"
          CIBW_TEST_COMMAND: "pytest {project}/tests/test_cpp_build.py -v"
          CIBW_ARCHS_MACOS: "universal2"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
